# Second Chance Quiz, Question 5 - Young's Modulus along any direction

In [1]:
#GIVENS

#lattice parameters, 
a = 5.54 #Å,
b = 4.87 #Å, 
c = 5.64 #Å, 

# angles in degrees
alpha_deg = 90 #º, 
beta_deg = 120.18 #º 
gamma_deg = 90 #º,

#angles in radians
import numpy as np
alpha = alpha_deg * np.pi /180
beta = beta_deg * np.pi /180
gamma = gamma_deg * np.pi /180

# mechanical coefficients (in GPa) 
c11 = 358
c12 = 144
c13 = 67
c15 = -25.9
c22 = 426
c23 = 127
c25 = 38.3
c33 = 240
c35 = -23.3
c44 = 99.1
c46 = -38.8
c55 = 78.7
c66 = 130

### Use Stiffness/Compliance relationships, to get Young's Modulus in the direction

$$ \frac{1}{E(n)} = s_{ijkl} n_i n_j n_k n_l $$

where E(n) is young's modulus, and $\frac{1}{E(n)}$ is the inverse, $s_{ijkl}$ is the compliance tensor, and $n_i n_j n_k n_l$ represents the unit vector in the direction in the crystal basis.

$$ C_{ij} = \frac{1}{S_{ij}} $$

## Part A: full compliance matrix for this material


In [2]:
# stiffness matrix

C = np.array([
    [c11, c12, c13, 0, c15, 0],
    [c12, c22, c23, 0, c25, 0],
    [c13, c23, c33, 0, c35, 0],
    [0, 0, 0, c44, 0, c46],
    [c15, c25, c35, 0, c55, 0],
    [0, 0, 0, c46, 0, c66]
])
print(C)

[[358.  144.   67.    0.  -25.9   0. ]
 [144.  426.  127.    0.   38.3   0. ]
 [ 67.  127.  240.    0.  -23.3   0. ]
 [  0.    0.    0.   99.1   0.  -38.8]
 [-25.9  38.3 -23.3   0.   78.7   0. ]
 [  0.    0.    0.  -38.8   0.  130. ]]


In [3]:
# compliance matrix is inverse of stiffness matrix
S = np.linalg.inv(C)
print("Compliance matrix:")
print("S = ", S, "(GPa)^-1")

Compliance matrix:
S =  [[ 0.00345939 -0.0012911  -0.0001143   0.          0.00173296  0.        ]
 [-0.0012911   0.00355632 -0.00178194  0.         -0.00268317  0.        ]
 [-0.0001143  -0.00178194  0.0053766   0.          0.00242138  0.        ]
 [ 0.          0.          0.          0.011426    0.          0.00341022]
 [ 0.00173296 -0.00268317  0.00242138  0.          0.01529946  0.        ]
 [ 0.          0.          0.          0.00341022  0.          0.00871013]] (GPa)^-1


## PART B: Cacluate Young's Modulus along the [2 D3 1] direction

In [4]:
direction = np.array([2, 5, 1])

##### "All directions and planes are referred to in the crystallographic system." 
##### the mechanical coefficients are already in crystallographic, SO no metric tensor etc

# direction cosines = normalized direction vector components
dir_mag = np.linalg.norm(direction)
n = direction / dir_mag      # unit vector

n1, n2, n3 = n # n is the direction cosines
print(n)

[0.36514837 0.91287093 0.18257419]


In [5]:
# need a 6 component vector to work with the 6x6 matrix. 
# voigt vector form; leveraging S17 pp31-34
# voigt notation, create the column vector representing the direction cosines 
q = np.array([
    n1**2,# 11
    n2**2,# 22
    n3**2,# 33
    n2*n3,# 23
    n1*n3,# 13
    n1*n2 # 12
])

In [6]:
inv_E = q @ S @ q # 1/E(n), in 1/GPa
E_n = 1.0 / inv_E  # Young's modulus a in GPa

print("Young's modulus along [2 5 1]:", E_n, "GPa")


Young's modulus along [2 5 1]: 275.8053215498748 GPa
